# Generated by Django 4.1.1 on 2022-12-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaznik',
            name='nazov_firmy',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
